// ============================================================
// RAYNATERS TECH — All copy lives here.
// Edit copy without touching JSX.
// ============================================================

export const CONTENT = {
  brand: {
    name: 'Raynaters',
    full: 'Raynaters Tech Inc.',
    tagline: 'Built for businesses ready to compound.',
    bookHref: '/book',
  },

  announcement: {
    text: 'ONLY 12 BUILD SLOTS LEFT THIS QUARTER — BOOK YOUR FREE AUDIT',
  },

  nav: {
    links: [
      { label: 'How it works', href: '/#evolution' },
      { label: 'What we build', href: '/#industry' },
      { label: 'Case studies', href: '/case-studies' },
      { label: 'Resources', href: '/resources' },
    ],
    cta: 'Book Audit',
  },

  hero: {
    eyebrow: 'Custom AI systems · Live in under a week',
    h1Lines: [
      'We Deploy AI Agents That',
      'Pay For Themselves Within 90 Days',
      '— Or We Keep Building Until They Do.',
    ],
    sub: 'Our AI systems have saved businesses 47,000+ hours of manual work across the UK and Australia. No jargon, no endless strategy decks — just working systems that answer your calls, book your jobs and chase your admin.',
    primaryCta: 'Book Your Free Agent Audit',
    secondaryCta: 'See Case Studies',
    trustLabel: 'Active deployments shipping with',
    trustLogos: [
      'n8n',
      'Make',
      'LangGraph',
      'Zapier',
      'OpenAI',
      'Anthropic',
      'Slack',
      'HubSpot',
    ],
  },

  proof: {
    eyebrow: 'Proven results',
    title: 'Real outcomes from systems we’ve shipped.',
    sub: 'We study your business, then build and deploy the automation, agents, or software it actually needs. Here’s what that has delivered across 23 live builds.',
    stats: [
      {
        to: 47283,
        prefix: '',
        suffix: '',
        label: 'Operational hours reclaimed',
        context: 'Across all deployments · last 14 months',
        level: 0.96,
      },
      {
        to: 90,
        prefix: '<',
        suffix: ' days',
        label: 'Average time to full ROI',
        context: 'Or we keep building at zero cost',
        level: 0.7,
      },
      {
        to: 23,
        prefix: '',
        suffix: '',
        label: 'AI systems live in production',
        context: 'Running across the UK & Australia',
        level: 0.5,
      },
      {
        to: 11,
        prefix: '',
        suffix: 's',
        label: 'Average agent first-response',
        context: 'Down from 3+ hours, manual',
        level: 0.99,
      },
    ],
    footnote: 'Measured Mar 2025 → May 2026. Receipts on request.',
  },

  howItWorks: {
    eyebrow: 'How deployment works',
    title: 'From first call to live agent in four weeks.',
    sub: 'A fixed, transparent process. No "AI strategy decks", no open-ended retainers — you always know exactly what happens next.',
    trust: 'The exact process behind 23 live deployments across the UK & Australia',
    guaranteeChip: 'Backed by our 90-day ROI guarantee',
    steps: [
      {
        week: 'Week 01',
        tag: 'Audit',
        title: 'The free Agent Audit',
        body: 'We map your operation, score every workflow for automation ROI, and hand you a written projection — before you commit a penny.',
      },
      {
        week: 'Week 02',
        tag: 'Build',
        title: 'Fixed-scope build',
        body: 'We scope the highest-ROI agent, lock the price, and build on infrastructure you own. No hourly billing games.',
      },
      {
        week: 'Week 03',
        tag: 'Deploy',
        title: 'Deploy inside your stack',
        body: 'Your agent goes live in the tools you already run — Slack, HubSpot, n8n — with full documentation and a recorded hand-off.',
      },
      {
        week: 'Week 04',
        tag: 'Prove',
        title: 'Prove, then compound',
        body: "We measure against the projection and open the 90-day proof window. If it doesn't pay for itself, we keep iterating free.",
      },
    ],
  },

  suites: {
    eyebrow: 'What we automate',
    title: 'Agent suites for the work that drains your team.',
    sub: "Tool-agnostic builds across the functions where hours leak the most. If a workflow is repeatable, it's automatable.",
    items: [
      {
        icon: 'support',
        name: 'Customer Support',
        desc: 'Tier-1 resolution, ticket triage, refunds and escalation routing — answered in seconds, not hours.',
        metric: 'Sub-1-minute first response',
        tools: ['Zendesk', 'Intercom', 'Slack'],
      },
      {
        icon: 'revops',
        name: 'Revenue Operations',
        desc: 'Lead enrichment, scoring, routing and CRM hygiene that keep your pipeline clean without a human touching it.',
        metric: '11-second lead routing',
        tools: ['HubSpot', 'Salesforce', 'Clay'],
      },
      {
        icon: 'finance',
        name: 'Finance & Reporting',
        desc: 'Invoice reconciliation, reporting compilers and inventory sync that close your books — and your Fridays — earlier.',
        metric: '2-day close → hourly',
        tools: ['Xero', 'QuickBooks', 'Sheets'],
      },
      {
        icon: 'onboarding',
        name: 'Onboarding & Ops',
        desc: 'Client and employee onboarding sequencers that compress 11-day ramps into 2, documented end to end.',
        metric: '11 days → 2 days',
        tools: ['Notion', 'Gmail', 'Calendar'],
      },
    ],
  },

  dashboardWall: {
    eyebrow: 'The receipts',
    title: 'A wall of working agents. Not slide decks.',
    sub: 'A live snapshot of dashboards, workflow runs, and Slack channels from systems we run for clients. Names redacted; hours are real.',
    tiles: [
      { kind: 'workflow', label: 'Inventory reconciliation · n8n', runs: '14,238 runs', status: 'Healthy', span: 'lg' },
      { kind: 'slack', label: '#agent-support — DTC apparel', detail: 'Resolved 412 tickets · last 7 days', span: 'sm' },
      { kind: 'metric', label: 'Hours reclaimed (90d)', value: '6,418', span: 'sm' },
      { kind: 'workflow', label: 'Lead enrichment · Make', runs: '92,401 runs', status: 'Healthy', span: 'md' },
      { kind: 'loom', label: 'Follow-up checker · live in n8n', duration: 'Active', span: 'md', image: '/n8n-workflow.png' },
      { kind: 'metric', label: 'Avg. first-response', value: '11s', span: 'sm' },
      { kind: 'workflow', label: 'Onboarding sequencer · LangGraph', runs: '3,902 runs', status: 'Healthy', span: 'md' },
      { kind: 'slack', label: '#agent-ops — SaaS analytics', detail: 'Auto-triaged 1,204 events', span: 'sm' },
      { kind: 'metric', label: 'Tickets / agent / day', value: '218', span: 'sm' },
      { kind: 'loom', label: 'Full workflow walkthrough', duration: '2:38', span: 'lg', video: '/walkthrough.mp4' },
      { kind: 'workflow', label: 'Reporting compiler · Python', runs: '1,138 runs', status: 'Healthy', span: 'sm' },
      { kind: 'metric', label: 'Cost saved (USD)', value: '$418k', span: 'sm' },
    ],
  },

  personalNote: {
    eyebrow: 'A note from the founder',
    name: 'Founder',
    role: 'Raynaters Tech Inc.',
    paragraphs: [
      "Hey — I'm the founder of Raynaters Tech Inc.",
      "Here's what I've set up for you, no strings:",
    ],
    bullets: [
      'A free 30-minute Agent Audit where I personally walk through your operation and identify exactly which workflows are automatable.',
      'A custom ROI projection delivered within 48 hours of the call — actual numbers, not vibes.',
      "If we're a fit, you'll get a fixed-scope deployment quote (no hourly billing games).",
      "If we're not, I'll send you 3 free recommendations and we'll part ways. No pressure.",
    ],
    closer: "You're not committing to anything. You're just getting clarity.",
    signature: '— Founder, Raynaters Tech Inc.',
  },

  why: {
    eyebrow: 'Founder honesty',
    title: "Why I'm Doing This (Call Me Selfish)",
    body: "Every agent we deploy that actually pays for itself becomes a case study. Every case study compounds our reputation. Every reputation point makes the next deal easier to close. So yes — call me selfish. I need you to win, because that's how Raynaters becomes the default name in agentic AI for businesses like yours.",
    punch: 'The fastest way for me to grow is to make you absurdly profitable.',
    attribution: 'Founder, Raynaters Tech Inc.',
  },

  authority: {
    value: 2400000,
    display: '$2.4M+',
    label: 'in operational cost cut across Raynaters deployments to date',
    footnote: 'Compounded across 23 active engagements · UK / US / EU / UAE',
  },

  guarantee: {
    eyebrow: 'Risk reversal — in writing',
    title: 'The risk is ours. In writing.',
    sub: 'Most agencies sell you a deck and disappear. We put our fee on the line — twice — so the only thing you can lose is the hours you are already losing.',
    layers: [
      {
        n: '01',
        label: '14-day full refund',
        proof: 'Same-day · no questions',
        body: 'No forms, no "are you sure?" emails. Change your mind in the first two weeks and we wire it back the same day.',
      },
      {
        n: '02',
        label: 'The 90-day ROI promise',
        proof: 'Up to 12 months free iteration',
        body: "If your system doesn't pay for itself within 90 days, we keep improving it at zero additional cost until it does.",
      },
    ],
    stat: {
      value: '0',
      label: 'Times we have had to invoke Layer 02',
    },
    closer: "We've never had to. We're not afraid to.",
    cta: 'Book your free Agent Audit',
  },

  testimonials: {
    rating: '4.9',
    reviewCount: '127 verified',
    title: 'They came for the pilot. They stayed for the compounding.',
    sub: 'A wall of unedited words from owners, operations leads and founders who put our systems to work.',
    items: [
      {
        name: 'Daniel A.',
        role: 'Head of Ops, fintech',
        initials: 'DA',
        avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'The audit alone was worth the time. We deployed a single agent and recovered the entire engagement fee inside seven weeks.',
        kind: 'slack' as const,
        meta: '#wins',
        company: 'Finchpay',
      },
      {
        name: 'Imogen R.',
        role: 'Founder, B2B SaaS',
        initials: 'IR',
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'I expected slides. I got a working agent in 18 days. The hand-off documentation is the cleanest I have ever seen from a vendor.',
        kind: 'email' as const,
        meta: 'Re: 18-day audit — wow.',
        email: 'imogen@northbound.io',
      },
      {
        name: 'Carlos M.',
        role: 'COO, logistics',
        initials: 'CM',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'We replaced an entire vendor contract with two Raynaters-built agents. The cost gap pays a junior hire every quarter.',
        kind: 'slack' as const,
        meta: '#cost-savings',
        company: 'Routedeck',
      },
      {
        name: 'Yuki T.',
        role: 'Agency owner',
        initials: 'YT',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'Onboarding compressed from 11 days to 2. Clients notice. We win pitches we used to lose to bigger shops.',
        kind: 'imessage' as const,
        meta: 'Yesterday 8:14 PM',
      },
      {
        name: 'Aisha K.',
        role: 'VP Support, e-commerce',
        initials: 'AK',
        avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'First-response time went from 3 hours to under a minute. CSAT actually went up — the agent is more patient than my best human.',
        kind: 'slack' as const,
        meta: '#cs-wins',
        company: 'Braided',
      },
      {
        name: 'Theo L.',
        role: 'Founder, marketplace',
        initials: 'TL',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'These guys told me what NOT to automate. Refreshing. We shipped 2 agents instead of 7 and ROI hit week 6.',
        kind: 'imessage' as const,
        meta: 'Today 11:42 AM',
      },
      {
        name: 'Nadia S.',
        role: 'Director of RevOps',
        initials: 'NS',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'Our enrichment + routing agent routes leads in 11 seconds. Sales actually trusts the data. That alone justified the build.',
        kind: 'slack' as const,
        meta: '#revops',
        company: 'Plumes',
      },
      {
        name: 'Henrik J.',
        role: 'CTO, climate tech',
        initials: 'HJ',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'They are the only AI agency that talks about failure modes before they take your money. Then they ship anyway. Rare.',
        kind: 'email' as const,
        meta: 'Honest pre-engagement convos',
        email: 'h.jansson@circulate.co',
      },
      {
        name: 'Pooja D.',
        role: 'Head of CX',
        initials: 'PD',
        avatar: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'The 90-day guarantee is not a marketing line. They keep iterating. Two of our agents are now on v4 — at no extra cost.',
        kind: 'slack' as const,
        meta: '#engineering',
        company: 'Tideline',
      },
      {
        name: 'Will F.',
        role: 'Founder, dev tools',
        initials: 'WF',
        avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'Tool-agnostic, like they advertise. We were on Make, they migrated us to LangGraph cleanly when the workflow outgrew it.',
        kind: 'imessage' as const,
        meta: 'Thursday 2:31 PM',
      },
      {
        name: 'Elena V.',
        role: 'Ops Lead, hospitality',
        initials: 'EV',
        avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'Fixed scope, fixed price, fixed timeline. After three burned automation vendors, I almost did not believe it. Then they shipped.',
        kind: 'email' as const,
        meta: 'Finally — a vendor that ships.',
        email: 'elena@plate-co.com',
      },
      {
        name: 'Samir B.',
        role: 'CEO, recruiting',
        initials: 'SB',
        avatar: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'The "free recommendations if we are not a fit" is real — they actually told us we did not need an agent yet. Earned the trust.',
        kind: 'email' as const,
        meta: 'Trust earned',
        email: 'samir@upline.work',
      },
      {
        name: 'Marcus T.',
        role: 'Head of Growth, PropTech',
        initials: 'MT',
        avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'We were manually enriching 400 leads a week. Now it\'s fully automated — enriched, scored, and routed before our SDRs start their day. Pipeline velocity doubled.',
        kind: 'slack' as const,
        meta: '#pipeline',
        company: 'Keystone',
      },
      {
        name: 'Lucía M.',
        role: 'COO, legal tech',
        initials: 'LM',
        avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'Their scoping process is rigorous in the best way. They found two workflows we assumed were too complex to automate and shipped both in the first sprint.',
        kind: 'email' as const,
        meta: 'Scoping process — game-changer',
        email: 'lucia.m@coalfox.legal',
      },
      {
        name: 'Owen P.',
        role: 'Founder, InsurTech',
        initials: 'OP',
        avatar: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: "I've tried three automation shops before Raynaters. The difference is they build for the edge case, not just the happy path. Nothing breaks in production.",
        kind: 'imessage' as const,
        meta: 'Tuesday 9:05 AM',
      },
      {
        name: 'Farida A.',
        role: 'VP Operations, healthcare',
        initials: 'FA',
        avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'HIPAA-compliant, self-hosted, fully documented. We went from skeptical to running six agents in production. The 14-day refund gave us the confidence to start.',
        kind: 'email' as const,
        meta: 'Re: HIPAA-compliant deploy',
        email: 'faisha@vianova.health',
      },
      {
        name: 'James W.',
        role: 'CTO, media',
        initials: 'JW',
        avatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'The audit revealed we were wasting £18k/year on a tool we could replace with one agent. They built it in two weeks. I have never had a vendor pay for themselves before the kick-off call.',
        kind: 'email' as const,
        meta: 'Re: £18k savings found in audit',
        email: 'j.weston@arclight.media',
      },
      {
        name: 'Priya N.',
        role: 'Head of Product',
        initials: 'PN',
        avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'They embedded with our team like a co-founder, not a contractor. Full Slack access, daily async updates, shipped ahead of schedule.',
        kind: 'slack' as const,
        meta: '#product',
        company: 'Kindred',
      },
      {
        name: 'Tobias H.',
        role: 'Director of Engineering',
        initials: 'TH',
        avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'Usually I spend two weeks reviewing a vendor\'s architecture. Their documentation was so clean I approved it in an afternoon. The system has been running in prod for four months without a single page.',
        kind: 'email' as const,
        meta: 'Architecture review — approved',
        email: 't.holm@inverso.dev',
      },
      {
        name: 'Chiara B.',
        role: 'Founder, fashion-tech',
        initials: 'CB',
        avatar: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'We run a lean team. Three months after deploying the wholesale order agent it processes 300 orders a day, and one of my ops staff was redeployed to growth. Worth every pound.',
        kind: 'imessage' as const,
        meta: 'Yesterday 6:48 PM',
      },
      {
        name: 'Noah K.',
        role: 'Ops Manager, retail',
        initials: 'NK',
        avatar: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'Inventory reconciliation used to be a Friday nightmare. Now it runs every hour, flags exceptions in Slack, and my team closes 90 minutes earlier on Fridays.',
        kind: 'slack' as const,
        meta: '#ops-team',
        company: 'Shopline',
      },
      {
        name: 'Sofia R.',
        role: 'CEO, edtech',
        initials: 'SR',
        avatar: 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'I was burned by AI hype before. The Raynaters team was the first to tell me our best workflow was not a good automation candidate. That honesty is why I trusted them with the three that were.',
        kind: 'email' as const,
        meta: 'Re: Audit follow-up',
        email: 'sofia@learnsphere.ed',
      },
      {
        name: 'Arjun P.',
        role: 'Director of Sales',
        initials: 'AP',
        avatar: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'CRM hygiene was our weakest link. They built an enrichment agent that keeps every contact field updated without anyone touching it. Our forecast accuracy improved in the first month.',
        kind: 'slack' as const,
        meta: '#sales-wins',
        company: 'Northform',
      },
      {
        name: 'Maya L.',
        role: 'Head of Revenue, SaaS',
        initials: 'ML',
        avatar: 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'Renewals used to require a 90-minute manual pull. The agent handles it end-to-end — checks usage, drafts the email, queues it for one-click send. My CSM recovered eight hours a week.',
        kind: 'slack' as const,
        meta: '#cs-team',
        company: 'Plumes',
      },
      {
        name: 'Jack D.',
        role: 'COO, cybersecurity',
        initials: 'JD',
        avatar: 'https://images.unsplash.com/photo-1566753323558-173cf4d61580?w=96&h=96&fit=crop&crop=face&auto=format',
        quote: 'Compliance reporting was a quarterly two-day sprint. Now it\'s a Tuesday morning report that runs itself. Freed up our most senior analyst to focus on actual threat work.',
        kind: 'email' as const,
        meta: 'Compliance reporting fixed',
        email: 'j.dawson@northstack.sec',
      },
    ],
  },

  faq: {
    eyebrow: 'The questions everyone asks',
    title: 'Everything you would ask in the first ten minutes.',
    items: [
      {
        q: 'What exactly do you build?',
        a: 'Three things, depending on what your business actually needs: (1) automation systems — the repetitive workflows quietly eating your team\'s hours; (2) agentic AI systems — agents that read context, decide, and take action, not just follow rigid rules; and (3) custom software development when off-the-shelf tools simply can\'t do the job.',
      },
      {
        q: 'How fast can you deploy?',
        a: 'Most systems go live in under a week. We move from your free audit to a working, deployed build fast — larger multi-system projects run two to four weeks depending on scope.',
      },
      {
        q: 'How do you decide what to build for me?',
        a: 'We start by analysing your operation — where the hours leak, where errors creep in, where revenue stalls. Then we scope the highest-ROI system for your specific business and hand you a written projection before you commit a penny. We never sell a template.',
      },
      {
        q: 'What if my data is sensitive?',
        a: 'Every system runs on infrastructure you own. We never hold your data, and builds are security-aligned by default.',
      },
      {
        q: 'Do I need a technical team to maintain this?',
        a: 'No. We hand off with full documentation, video walkthroughs, and 90 days of post-launch support included.',
      },
      {
        q: 'What tools and stack do you build on?',
        a: "Whatever fits your business — we're tool-agnostic. n8n, Make, Zapier, custom Python, LangGraph, OpenAI and Anthropic models, and full custom codebases when the job calls for it.",
      },
      {
        q: "What's the typical investment?",
        a: 'Pilot builds start at £4,500. Full multi-system engagements range £15K–£60K depending on scope. You get an ROI projection before any commitment.',
      },
      {
        q: 'What happens after the free audit call?',
        a: "If we're a fit, you get a written proposal within 48 hours. If we're not, you get three free recommendations and we go our separate ways — no pressure.",
      },
    ],
  },

  finalCta: {
    eyebrow: 'Last call',
    title: 'Stop Doing What An Agent Could Do.',
    sub: 'Only 12 build slots left this quarter.',
    cta: 'Book Your Free Agent Audit',
    smallprint: 'Free 30-minute call. ROI projection within 48 hours. No pitch deck.',
  },

  footer: {
    tagline: 'Built for businesses ready to compound.',
    columns: [
      {
        label: 'Solutions',
        links: [
          { label: 'AI Automation Agency', href: '/ai-automation-agency-uk' },
          { label: 'AI for Law Firms', href: '/ai-automation-for-law-firms-uk' },
          { label: 'AI Receptionist · Trades', href: '/ai-receptionist-for-trades-uk' },
          { label: 'AI Receptionist · Clinics', href: '/ai-receptionist-for-clinics-uk' },
          { label: 'AI Receptionist · Cosmetic', href: '/ai-receptionist-for-cosmetic-clinics-uk' },
          { label: 'AI Receptionist Cost', href: '/ai-receptionist-cost-uk' },
        ],
      },
      {
        label: 'Company',
        links: [
          { label: 'How it works', href: '/#evolution' },
          { label: 'What we build', href: '/#industry' },
          { label: 'Case studies', href: '/case-studies' },
          { label: 'Resources', href: '/resources' },
          { label: 'Guarantee', href: '/#guarantee' },
          { label: 'FAQ', href: '/#faq' },
        ],
      },
      {
        label: 'Connect',
        links: [
          { label: 'Book audit', href: '/book' },
          { label: 'Email', href: 'mailto:team@raynaters.tech' },
          { label: 'LinkedIn', href: '#' },
        ],
      },
      {
        label: 'Legal',
        links: [
          { label: 'Privacy', href: '#' },
          { label: 'Terms', href: '#' },
        ],
      },
    ],
    copyright: '© 2026 Raynaters Tech Inc. All rights reserved.',
  },
} as const;

export type Content = typeof CONTENT;
